name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Restore 
      run: dotnet restore  ./EcommerceAPI.sln

    - name: Build
      run: dotnet build ./EcommerceAPI.sln --configuration Release 

    - name: Publish
      run: dotnet publish ./EcommerceAPI.sln --configuration Release --no-build
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ecommerce-api-app
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
        package: './publish'


    
